const pair = (en, ja) => ({ en, ja });
export const caseId = "NC-0417";
export const dossiers = [
  {
    id: "client-intake", code: "CI / 0417 / 01", revision: "02", day: 0, image: "consultation", publicPage: "relic",
    name: pair("Continuity Enrollment Record", "継承プログラム登録記録"), department: pair("Client Services / Night City", "顧客サービス / ナイトシティ"),
    summary: pair("Preservation accepted. Expectations require clarification.", "保存を受理。期待内容について説明が必要。"),
    annotation: pair("The daughter asked whether the appointment would still belong to her mother. The question was entered under scheduling.", "娘は、この面談が今後も母のものなのかと尋ねた。質問は日程調整の項目に記入された。"),
    sections: [
      [pair("Purpose of enrollment", "登録の目的"), pair("Case NC-0417 concerns a private client enrolled through the Night City office. The client requested preservation of a personality construct for subsequent family interaction. A daughter attended the consultation as the nominated correspondent. Neither participant requested biological host transfer. The intake officer explained that a Relic interface and a retained archive serve different functions; possession of a cartridge does not establish authority over the archive from which a construct is supplied.", "案件NC-0417は、ナイトシティ支店で登録した個人顧客に関するもの。顧客は、将来の家族との対話に向けて人格構築体の保存を希望した。娘が指定連絡者として面談に同席した。いずれも生物学的な宿主への移行は求めていない。担当者は、Relicの接続機能と保管アーカイブは別の役割を持ち、カートリッジの所持だけでは構築体の供給元アーカイブに対する権限を得られないと説明した。")],
      [pair("Client instructions", "顧客の指示"), pair("The client supplied a short recording describing preferred forms of address, family names, and a memory of waiting for a train with her daughter. These materials are contextual records, not an independent test of identity. The client asked that family interaction remain possible even if she could no longer confirm each appointment herself. This request was copied into the enrollment file. It was not converted into an unrestricted authorization, and Client Services must not describe it as one in subsequent correspondence.", "顧客は、呼び方、家族の名前、娘と列車を待った思い出を含む短い録音を提出した。これらは文脈資料であり、本人性を独立に判定する試験ではない。顧客は、自分が毎回の面談を承認できなくなっても家族との対話を継続できるよう希望した。この要望は登録記録に転記された。ただし無制限の承認に変更されたわけではなく、顧客サービスは今後の連絡でそのように説明してはならない。")],
      [pair("Scope acknowledged", "確認された範囲"), pair("Preservation, scheduled interaction, and release to another system were reviewed as separate activities. The daughter correctly repeated the distinction between a stored personality and a biological person. The client then asked whether the stored personality could make a different choice later. The officer recorded the question without supplying a definitive answer. Enrollment language establishes the agreed service scope; it does not resolve the status of a construct's future preferences. No promise of unlimited visits, perpetual availability, or personal survival was entered in the file.", "保存、予約された対話、別システムへの引き渡しは、異なる行為として確認された。娘は、保存人格と生物学的な本人との違いを正しく言い直した。その後、顧客は保存人格が将来別の選択をできるのかと尋ねた。担当者は断定的な回答をせずに質問を記録した。登録文言は合意されたサービス範囲を定めるものであり、構築体の将来の希望の扱いを解決するものではない。無制限の面会、永続的な利用可能性、本人の生存を約束する記載はない。")],
      [pair("Transfer and correspondence", "移管と連絡"), pair("The enrollment packet was accepted for controlled custody. Regional staff retained the family correspondence while the archive reference entered the technical register. The daughter is authorized to submit requests, not to instruct archive operations. Any later request for removal, independent custody, or a different interaction channel must pass through the access review process. Staff should preserve the client's original wording alongside the standardized summary, including questions that do not fit the available form fields. Receipt of the packet confirms receipt only; it must not be used as a completion certificate. The daughter left a second contact number in the margin, explaining that the family apartment was quiet after the evening train. The number was entered in the contact register; the explanation was retained with the recording.", "登録資料は管理保管の対象として受理された。地域担当者は家族との通信を保持し、アーカイブ参照番号は技術台帳に登録された。娘は要望を提出できるが、アーカイブ運用を指示する権限は持たない。今後、取り出し、独立した保管、異なる対話経路が求められた場合は、アクセス審査を通すこと。様式の項目に収まらない質問も含め、標準化された要約と顧客の原文を併せて保存すること。資料の受領は受領のみを示し、完了証明として使用してはならない。娘は余白に二つ目の連絡先を記し、夕方の列車が去ると家の中が静かになると説明した。番号は連絡先台帳へ登録し、説明は録音とともに保持した。")],
    ],
  },
  {
    id: "access-review", code: "AR / 0417 / 02", revision: "03", day: 18, image: "transport", publicPage: "mikoshi",
    name: pair("Construct Access Review", "構築体アクセス審査"), department: pair("Archive Custody / Regional Counsel", "アーカイブ管理 / 地域法務"),
    summary: pair("Family recognition does not amend the custody instruction.", "家族による認識は、保管指示を変更しない。"),
    annotation: pair("Correspondence retains the phrase 'bring her home.' The disposition field uses 'external release.'", "通信記録には「母を家に連れて帰る」とある。処理欄では「外部引き渡し」と表記されている。"),
    sections: [
      [pair("Request received", "受理した要望"), pair("At the first scheduled interaction following archive acceptance, the daughter reported that the construct recognized a family expression absent from the enrollment recording. She requested that the next appointment occur outside the regional consultation facility. Her stated reason was simple: her mother had never liked offices. Client Services referred the request as a change of interaction channel. Archive Custody classified it as a proposed external release because the requested arrangement would place the construct beyond the currently approved custody environment.", "アーカイブ受理後の初回対話で、娘は登録時の録音にない家族特有の表現を構築体が理解したと報告した。次回の面談を地域相談施設の外で行うことを希望した。理由は、母が昔から事務所を好まなかったためだという。顧客サービスは対話経路の変更として照会した。アーカイブ管理は、承認済みの保管環境の外に構築体を置くことになるため、外部引き渡しの申請として分類した。")],
      [pair("Authority examined", "権限の確認"), pair("The enrollment record names the daughter as correspondent. It does not name her as archive operator or authorize independent export. Recognition of private memories may be relevant to the family's experience, but it cannot substitute for an instruction in the custody record. Counsel requested the exact wording of the client's original preference. The sentence concerning continued family interaction was present. It did not specify location, a release mechanism, or the treatment of a later instruction expressed by the stored personality. These omissions should be described as unresolved scope, not as evidence that the client opposed release.", "登録記録では娘を連絡者として指定している。アーカイブの運用者とはしておらず、独立した持ち出しも承認していない。個人的な記憶の認識は家族の体験に関係するが、保管記録上の指示を代替するものではない。法務は顧客の希望の原文を求めた。家族との対話継続に関する文は存在した。しかし場所、引き渡し方法、保存人格が後に示す意思の扱いは定められていなかった。この不足は範囲の未確定として説明し、顧客が引き渡しに反対した証拠として扱ってはならない。")],
      [pair("Interim treatment", "暫定的な対応"), pair("No external release is approved while the instruction remains under review. Existing scheduled interaction may continue within its prior scope; this decision is not a technical finding that a new channel would be unsafe. Security has been asked to retain the cartridge movement record and identify the responsible custodians. Banking relationship staff may verify the correspondent's identity, but financial standing must not be described as proof of consent. The archive remains retained. There is no instruction in this review to delete, alter, or suppress the construct.", "指示の審査中は外部引き渡しを承認しない。既存の予約対話は従来の範囲内で継続できる。この判断は、新しい経路が危険であるとの技術的認定ではない。警備にはカートリッジ移動記録の保存と管理責任者の特定を求めた。銀行の顧客担当は連絡者の本人確認を行えるが、資産状況を同意の証拠として説明してはならない。アーカイブの保管は継続する。本審査には構築体の削除、改変、抑制の指示はない。")],
      [pair("Question referred", "照会した問題"), pair("The daughter asked whether her mother's request would count if the construct made it directly. Counsel cannot resolve that question from an enrollment form. Research is asked to distinguish a recognizable response from an assessment of identity and preference. Client Services should acknowledge the question without promising that the technical assessment will determine custody rights. The family must receive one consistent account of the review, rather than separate answers from departments using the same word, continuity, to describe different things. No completion date is authorized for that assessment.", "娘は、構築体が直接求めた場合に母の要望として認められるのかと尋ねた。法務は登録用紙だけから判断できない。研究部門には、認識できる応答と本人性・希望の評価を区別するよう求めた。顧客サービスは質問を受け止めつつ、技術評価によって保管上の権利が決まると約束してはならない。各部門が「継承」という同じ言葉で異なるものを指して別々の回答をするのではなく、家族には一貫した審査説明を届けること。評価の完了日は承認されていない。")],
    ],
  },
  {
    id: "identity-assessment", code: "IA / 0417 / 03", revision: "01", day: 26, image: "mikoshi", publicPage: "engram-technology",
    name: pair("Identity Assessment", "本人性評価"), department: pair("Neural Representation / Research", "神経表現 / 研究部門"),
    summary: pair("Recognition established. Continuity remains an open question.", "認識を確認。連続性の問題は未解決。"),
    annotation: pair("The session transcript includes: 'She knows where the station was.' The technical summary includes: 'Contextual recall observed.'", "対話記録には「母は駅の場所を覚えている」とある。技術要約には「文脈に沿った想起を観測」とある。"),
    sections: [
      [pair("Assessment boundary", "評価の範囲"), pair("Research reviewed the enrollment recording and the authorized interaction transcript for case NC-0417. This is a limited review of recorded responses, not an unrestricted examination of the archive. The construct used the client's preferred address and described the railway memory with details the daughter recognized. These observations support a finding of recognizable contextual recall in the reviewed material. They do not, by themselves, establish that an original subjective experience has continued, or that every remembered detail is independently verifiable.", "研究部門は案件NC-0417の登録録音と承認された対話記録を確認した。これは記録された応答の限定的な検討であり、アーカイブ全体を無制限に調べるものではない。構築体は顧客が希望した呼び方を使用し、娘が認識できる細部を含めて列車の思い出を述べた。確認資料内での文脈に沿った想起を認定する根拠となる。ただし、それだけで元の主観的経験の継続や、すべての記憶の独立した検証可能性が証明されるわけではない。")],
      [pair("Functions kept separate", "機能の区別"), pair("The production of a personality representation, its retention within Mikoshi, and its presentation through Relic are separate functions. A successful interaction does not answer every question about the representation's origin or its status. Reviewers must avoid treating interface fluency as a measurement of personal survival. Equally, the absence of a conclusive survival measurement must not be rewritten as a finding that the family's recognition is false. Both statements go beyond the evidence examined. This report is not a specification for creating or transferring a construct.", "人格表現の生成、ミコシでの保持、Relicを通した提示は別々の機能である。対話の成功だけで、その表現の起源や地位に関するすべての問いに答えられるわけではない。審査者は接続上の応答の自然さを、本人の生存の測定値として扱ってはならない。同様に、決定的な生存測定がないことを、家族の認識が誤りだとの認定に書き換えてはならない。どちらも確認した証拠を超える。本報告は構築体の生成や移行の仕様書ではない。")],
      [pair("Preference in the record", "記録内の希望"), pair("The reviewed transcript contains a request to speak to the daughter again. Research can record that the response occurred in context. It cannot determine whether the response carries the authority of a new custody instruction. That is a policy question with technical evidence attached, not a technical question with a policy answer concealed inside it. If counsel relies on this report, the limitation must travel with the finding. Extracting the phrase recognizable contextual recall without the surrounding qualification would materially change the report's meaning.", "確認した対話記録には、娘と再び話したいとの要望がある。研究部門は、その応答が文脈の中で生じたことを記録できる。しかし新たな保管指示としての権限を持つかは判断できない。これは技術的証拠を伴う方針上の問題であり、方針上の答えを技術判断の中に隠すべき問題ではない。法務が本報告を使用する場合は、認定とともに限界も示すこと。「文脈に沿った想起」の部分だけを条件抜きで抽出すると、報告の意味が実質的に変わる。")],
      [pair("Unanswered does not mean absent", "未解決と不存在の違い"), pair("The unresolved question is not whether the daughter experienced recognition. She did, and the correspondence should retain her account. The unresolved question is what the institution is entitled to infer from it. Additional recorded interactions may supply more observations without settling that distinction. Research therefore returns the file with a bounded finding and an open qualification. Client Services should not tell the family that the system has answered a question the report explicitly leaves unanswered. No change to custody is recommended on the basis of this assessment alone. The railway memory appears in both records, but in the later interaction the construct asks whether the daughter still waits on the same side of the platform. Research records the question. It does not classify the daughter's pause before answering.", "未解決なのは、娘が母を認識したと感じたかどうかではない。その体験はあり、通信記録には本人の説明を残すべきである。未解決なのは、組織がそこから何を推論する権限を持つかである。対話記録を増やせば観測は増えるが、この区別が解消するとは限らない。研究部門は、限定的な認定と未解決の留保を付して記録を返す。報告が明示的に未回答とした問いにシステムが答えたと、家族へ伝えてはならない。本評価だけを根拠に保管を変更することは推奨しない。列車の記憶は両方の記録に現れるが、後の対話では、構築体が娘に今もホームの同じ側で待つのかと尋ねている。研究部門はその質問を記録する。答える前に娘が置いた間については分類しない。")],
    ],
  },
  {
    id: "succession-directive", code: "SD / 0417 / 04", revision: "04", day: 31, image: "headquarters", publicPage: "company",
    name: pair("Executive Succession Directive", "経営継承指令"), department: pair("Group Secretariat / Tokyo", "グループ事務局 / 東京"),
    summary: pair("An exceptional mandate is not a general entitlement.", "例外的な委任は、一般的な権利ではない。"),
    annotation: pair("The family asked why restoration changes what the company may promise, but not what the client may request.", "家族は、復帰によって企業が約束できる内容は変わるのに、顧客が求められる内容は変わらない理由を尋ねた。"),
    sections: [
      [pair("Reason for circulation", "配布の理由"), pair("Regional counsel requested clarification after the correspondent in NC-0417 cited Saburo Arasaka's restored leadership in support of an external release request. The family understood the public announcement as evidence that continuity could include a return to independent life. This directive concerns the scope of that inference. It does not amend the research assessment or assert that the commercial interaction program and executive restoration are technically identical. The group must describe its public achievements without allowing unlike applications to become interchangeable in client correspondence.", "NC-0417の連絡者が、外部引き渡しの要望の根拠としてサブロウ・アラサカの指導体制への復帰を挙げたため、地域法務が説明を求めた。家族は、公表内容を独立した生活への復帰も継承に含まれ得る証拠と理解した。本指令はその推論の範囲に関するものである。研究評価を変更せず、商用対話プログラムと経営者の復帰が技術的に同一だと主張するものでもない。グループは公的な成果を説明する際、異なる用途が顧客への説明で交換可能なものとして扱われないようにすること。")],
      [pair("Institutional mandate", "組織としての委任"), pair("Leadership restoration belongs to an exceptional institutional mandate. Ordinary enrollment does not confer that mandate, and the restoration of group leadership does not automatically expand an existing private agreement. This distinction is to be stated plainly. It must not be presented as a finding that ordinary clients lack meaningful memories or recognizable personalities. The exception concerns what the institution has chosen to authorize. No staff member is empowered by this directive to promise a comparable pathway, to invent eligibility criteria, or to offer an accelerated review in exchange for a financial relationship.", "指導体制への復帰は、例外的な組織の委任に属する。通常の登録でその委任を得ることはなく、経営者の復帰によって既存の個人契約が自動的に拡張されることもない。この違いは明確に伝えること。一般顧客には意味のある記憶や認識可能な人格がないという認定として説明してはならない。例外は、組織が何を承認することを選んだかに関する。本指令によって、同等の経路を約束し、資格条件を作り、金融関係と引き換えに審査を早める権限を職員に与えるものではない。")],
      [pair("Response to the family", "家族への回答"), pair("The correspondent is entitled to a coherent explanation of the service actually enrolled. She is not to be sent between departments for a question each department can identify but none will answer. Counsel should distinguish three matters: the evidence available about this construct, the permissions recorded for this account, and the institution's separate executive mandate. The first remains qualified by Research. The second remains bounded by the intake record. The third is not a precedent granting release in this case. Avoid the phrase technical impossibility where the decision is an authorization decision.", "連絡者には、実際に登録したサービスについて一貫した説明を届けること。各部門が問題を理解しながら誰も答えないまま、家族を部門間で行き来させてはならない。法務は、構築体に関する証拠、この契約に記録された許可、組織の別個の経営者向け委任の三点を区別すること。第一は研究部門の留保付きの認定、第二は登録記録の範囲に限られ、第三は本件で引き渡しを認める先例ではない。承認に関する判断を「技術的に不可能」と言い換えてはならない。")],
      [pair("Record retention", "記録の保存"), pair("Retain the family's comparison with the public announcement in the case file. It is relevant to expectations even where it does not alter permissions. The Secretariat requires a final disposition that identifies both the administrative result and the unresolved personal question. A case may be closed as a review without being described as a resolution of identity. The distinction is necessary for institutional accuracy. Distribution identifiers for individual reviewers are withheld in this copy; the decision and its limitations are not withheld. This directive does not instruct the removal of any prior correspondence.", "家族による公表内容との比較は案件記録に残すこと。許可を変更しなくても期待内容に関係する。事務局は、行政的な結果と未解決の個人的な問いの両方を示す最終処理を求める。審査を終結することと、本人性の問題を解決したと説明することは別である。組織として正確な記録を保つため、この区別が必要になる。本写しでは個別審査者の配布識別情報を非開示とするが、判断とその限界は非開示にしない。過去の通信を取り除く指示はない。")],
    ],
  },
  {
    id: "case-disposition", code: "CD / 0417 / 05", revision: "01", day: 44, image: "review-terminal", publicPage: "banking",
    name: pair("Case Disposition", "案件処理記録"), department: pair("Client Services / Records Office", "顧客サービス / 記録室"),
    summary: pair("Review closed. Archive retained. Question unresolved.", "審査終結。保存継続。問いは未解決。"),
    annotation: pair("The last family message contains no request for another review. It asks whether the message can be passed on.", "家族からの最後の連絡には再審査の要望がない。メッセージを伝えてもらえるかと尋ねている。"),
    sections: [
      [pair("Administrative result", "管理上の結果"), pair("The external release request in case NC-0417 is not approved under the recorded enrollment scope. The archive is retained. Previously authorized interaction remains within its existing scope, subject to the same review process for any change. There is no deletion instruction and no finding that the construct failed recognition. Client Services has delivered the written disposition to the nominated correspondent. The review is now closed for administrative purposes. Closure must not be reported as proof that the family's question about personal continuity has been resolved.", "案件NC-0417の外部引き渡しは、記録された登録範囲では承認しない。アーカイブの保持は続ける。既に承認された対話は従来の範囲内に留まり、変更には同じ審査を適用する。削除指示はなく、構築体の認識に失敗があったとの認定もない。顧客サービスは指定連絡者に処理通知を書面で届けた。審査は管理上の目的で終結する。家族が尋ねた個人の連続性が解決した証拠として、終結を報告してはならない。")],
      [pair("Findings carried forward", "引き継ぐ認定"), pair("The intake record preserves the client's wish for continued family interaction. The access review establishes that this wish did not specify an independent release. Research records recognizable contextual recall while leaving subjective continuity unresolved. The Secretariat distinguishes executive restoration from an ordinary enrollment entitlement. None of these records cancels the others. The final summary must retain the sequence rather than replacing it with a single statement that the client lacked authorization. That shorter statement would omit the expectation on which the request was made and the question the review could not settle.", "登録記録は家族との対話継続という顧客の希望を保持する。アクセス審査では、その希望に独立した引き渡しの指定がなかったことを確認した。研究部門は文脈に沿った想起を記録し、主観的連続性を未解決とした。事務局は経営者の復帰と通常登録の権利を区別した。どの記録も他を取り消さない。最終要約はこの経緯を残し、「顧客に権限がなかった」という一文に置き換えてはならない。その短い説明では、要望の基礎となった期待と、審査で解決できなかった問いが抜け落ちる。")],
      [pair("Final correspondence", "最終の通信"), pair("The daughter acknowledged receipt without accepting the explanation as an answer to her original question. She submitted a short message intended for her mother, referring again to the railway platform described at intake. The message contains no new custody instruction. It has been attached to the interaction correspondence record rather than converted into an appeal. Staff should not infer that the absence of an appeal indicates satisfaction. Delivery of the message to a future session is not certified by this disposition. The record confirms only that it was received and retained.", "娘は通知の受領を認めたが、それを最初の問いへの回答として受け入れたわけではない。母に宛てた短いメッセージを提出し、登録時に話した駅のホームに再び触れた。新しい保管指示は含まれていない。不服申立てに変換せず、対話に関する通信記録に添付した。不服申立てがないことを満足の表れと推論してはならない。この処理記録は、将来の対話でメッセージが届けられることを証明しない。受領と保持のみを確認する。")],
      [pair("Institutional status", "組織上の状態"), pair("Security retains the movement record. Archive Custody retains the construct reference. The banking relationship file retains the correspondent's verified identity. Research retains its qualified assessment. Each department has completed the action assigned to it. No department has established who may answer on the client's behalf when the stored personality asks for something the enrollment form did not anticipate. That question remains in the file. The institution can account for the cartridge, the instruction, and the correspondence. The daughter's remaining question concerns the person. Do not remove that distinction from subsequent summaries.", "警備は移動記録を、アーカイブ管理は構築体参照を、銀行の顧客記録は確認済みの連絡者情報を保持する。研究部門は留保付きの評価を保持する。各部門は割り当てられた処理を完了した。しかし保存人格が登録用紙の想定しないことを求めたとき、誰が顧客に代わって答えられるかは、どの部門も確定していない。その問いは記録に残る。組織はカートリッジ、指示、通信を管理できる。娘がなお尋ねているのは、その人についてである。以後の要約からこの違いを取り除いてはならない。")],
    ],
  },
];

export const fieldStories = {
  home: { image: "consultation", title: pair("A voice is only the beginning.", "声は、始まりにすぎない。"), eyebrow: pair("Relic / Human continuity", "Relic / 人の継承"), copy: pair("A familiar expression. A memory only your family shares. Relic brings a stored personality into conversation. Behind that encounter lies another institution: the archive that holds the construct, the people authorized to request access, and the instructions that govern what happens next.", "聞き覚えのある言い回し。家族だけが知る記憶。Relicは保存された人格との対話を可能にします。その出会いの背後には、構築体を保持するアーカイブ、アクセスを求める権限を持つ人、そして次に何が起きるかを定める指示があります。"), target: "relic" },
  businesses: { image: "transport", title: pair("One cartridge. Three businesses.", "一つのカートリッジ。三つの事業。"), copy: pair("A neural cartridge crosses a secured counter. Security records its movement. Financial relationship teams establish who may give instructions. Technology maintains the construct and the interface. Arasaka's strength is not simply the breadth of its portfolio. It is the ability to keep custody, authority, and engineering inside the same institution.", "神経カートリッジが管理された窓口を通過します。警備が移動を記録し、金融の顧客担当が指示権限を確認し、技術部門が構築体と接続基盤を維持します。アラサカの力は事業の幅広さだけではありません。保管、権限、工学を一つの組織に収めることにあります。"), target: "technology" },
  security: { image: "night-city", title: pair("The threshold matters.", "境界を守る。"), copy: pair("In Night City, protective operations and the distribution of Japanese-made equipment form part of Arasaka's regional presence. A corporate perimeter is more than a wall: it separates visitors from staff, cargo from cleared equipment, and a request from an authorized movement. Regional command connects those decisions to the wider group.", "ナイトシティでは、警護業務と日本製装備の流通がアラサカの地域展開を担います。企業の境界は壁だけではありません。訪問者と職員、貨物と承認済み装備、要望と許可された移動を区別します。地域の指揮系統が、これらの判断をグループ全体につなぎます。"), target: "contact" },
  banking: { image: "consultation", title: pair("Inheritance begins with an instruction.", "継承は、指示から始まる。"), copy: pair("A family relationship can continue long after the person who established it can approve a transaction. Records must distinguish a beneficiary, a nominated correspondent, and a person authorized to act. The same distinction becomes more consequential when the retained asset includes a personality construct. Financial identity, family recognition, and archive authority are not interchangeable.", "金融関係を築いた本人が取引を承認できなくなっても、家族との関係は続きます。記録では受益者、指定連絡者、行為を承認された人を区別する必要があります。保持する資産に人格構築体が含まれると、その区別はさらに重要になります。金融上の本人確認、家族による認識、アーカイブへの権限は同じではありません。"), dossier: "case-disposition" },
  technology: { image: "manufacturing", title: pair("From representation to interface.", "人格表現から、接続へ。"), copy: pair("An engram is not a cartridge, and a cartridge is not an archive. Research examines the representation of personality; precision manufacturing gives the interface a physical form; dedicated infrastructure retains the construct. The restored era brings these disciplines into closer alignment without making their functions identical.", "エングラムはカートリッジではなく、カートリッジはアーカイブではありません。研究は人格表現を扱い、精密製造は接続基盤を物理的な形にし、専用インフラは構築体を保持します。復帰後の時代はこれらの分野を連携させますが、機能が同一になるわけではありません。"), target: "engram-technology" },
  products: { image: "manufacturing", title: pair("The object and the institution behind it.", "製品と、その背後の組織。"), copy: pair("A smart pistol and a neural biochip address different needs. Both belong to a portfolio in which manufactured objects connect to a larger operating environment. Read the product profiles for platform roles and compatibility context, rather than invented performance figures. The archive, the interface, and the equipment each have a distinct place in the group.", "スマート・ピストルと神経バイオチップは異なる用途を持ちます。いずれも、製造された物体をより大きな運用環境に結びつける製品群の一部です。製品概要では架空の性能値ではなく、役割と対応環境を紹介します。アーカイブ、接続基盤、装備は、それぞれグループ内で異なる位置を占めます。"), target: "research" },
  relic: { image: "consultation", title: pair("The conversation. The record. The next visit.", "対話。記録。そして次の面会。"), copy: pair("Commercial Relic interaction concerns a stored personality, not an ordinary promise of biological return. A familiar response can matter deeply to a family while leaving other questions open. Who may request another encounter? Which instructions remain in force? The interface makes the conversation possible. The institution determines its scope.", "商用Relicの対話が扱うのは保存人格であり、生物学的な復帰を通常のサービスとして約束するものではありません。親しみのある応答は家族に深い意味を持つ一方、別の問いを残します。次の面会を誰が求められるか。どの指示が有効か。接続基盤が対話を可能にし、組織がその範囲を定めます。"), dossier: "client-intake" },
  mikoshi: { image: "transport", title: pair("Retention is not release.", "保持と引き渡しは、別のもの。"), copy: pair("The archive and the point of interaction are different parts of the engram environment. A construct retained within Mikoshi is not the same thing as the cartridge presented at a consultation. In the group's custody model, movement, access, and authority are recorded separately. A preserved personality raises a question no storage diagram can settle: who should be allowed to speak for it?", "アーカイブと対話の接点は、エングラム環境の異なる部分です。ミコシに保持される構築体と、面談で使われるカートリッジは同じものではありません。グループの管理モデルでは、移動、アクセス、権限を別々に記録します。保存人格は、保管の図だけでは解けない問いを生みます。誰がそれに代わって発言できるのでしょうか。"), dossier: "access-review" },
  shingen: { image: "manufacturing", title: pair("A family of smart systems.", "スマートシステムの製品群。"), copy: pair("The TKI-20 designation identifies Shingen within Arasaka's smart weapon portfolio. Its submachine-gun format differs from the HJKE-11 Yukimura pistol; their shared smart classification does not make them the same platform. Hardware, targeting interfaces, and regional equipment support belong to the wider manufacturing business. Each format retains its own designation and operating context.", "TKI-20という型式は、アラサカのスマート兵器群におけるシンゲンを識別します。サブマシンガン形式はHJKE-11ユキムラのピストル形式とは異なり、同じスマート分類でも同一の製品ではありません。ハードウェア、照準接続、地域の装備支援は、より広い製造事業に属します。各形式は、独自の型式と運用上の位置づけを持ちます。"), target: "security" },
  yukimura: { image: "manufacturing", title: pair("Compact hardware. A wider system.", "小型装備。広がる体系。"), copy: pair("HJKE-11 Yukimura brings the smart weapon class into a pistol format. Its role in the portfolio is distinct from Shingen's compact submachine-gun platform. The product belongs to a manufacturing institution, not an isolated catalogue entry: regional distribution, professional equipment relationships, and compatible interfaces give the object its operating context.", "HJKE-11ユキムラはスマート兵器をピストル形式に展開します。製品群における役割は、小型サブマシンガンであるシンゲンと異なります。これは単独のカタログ項目ではなく、製造組織に属する製品です。地域流通、専門装備との関係、対応する接続環境が運用の文脈を与えます。"), target: "shingen" },
  research: { image: "manufacturing", title: pair("What a response can establish.", "応答から、何を確かめられるか。"), copy: pair("A recognizable memory is an observation. A claim that a person has survived is a different conclusion. Engram research must distinguish representation, interaction, and biological restoration, even when public language calls all three continuity. The boundary matters most when a technical finding is used to make a decision about someone else.", "認識できる記憶は観測です。本人が生存しているという主張は別の結論です。エングラム研究では、表現、対話、生物学的な復元を区別する必要があります。公的な言葉ですべてを継承と呼ぶ場合も同様です。技術認定が他者に関する判断に使われるとき、その境界は特に重要になります。"), dossier: "identity-assessment" },
  "engram-technology": { image: "review-terminal", title: pair("Three functions. One unresolved question.", "三つの機能。一つの未解決の問い。"), copy: pair("Soulkiller, Mikoshi, and Relic describe the creation, retention, and interface of a personality construct. That functional relationship is not a proof of subjective continuity. A system can retain a representation and enable recognizable interaction while leaving the status of the original person unanswered. Technical language should preserve that distinction, not conceal it.", "ソウルキラー、ミコシ、Relicは、人格構築体の生成、保持、接続を担います。この機能上の関係は、主観的連続性の証明ではありません。表現を保持し、認識可能な対話を可能にしても、元の本人の地位は未解決のまま残り得ます。技術的な言葉は、その違いを隠さずに保つべきです。"), dossier: "identity-assessment" },
  company: { image: "night-city", title: pair("The family. The institution. The mandate.", "一族。組織。そして委任。"), copy: pair("Saburo Arasaka's restored leadership places succession at the center of the group's next chapter. In this restored era, the family name is more than an identity on a tower: it defines whose direction the institution carries forward. Executive restoration and commercial personality interaction remain separate applications. The distinction shapes both the public promise and the private decisions behind it.", "サブロウ・アラサカの指導体制への復帰は、継承をグループの次の章の中心に置きます。この時代における一族の名は、塔の上の名称だけではありません。組織が誰の方針を受け継ぐかを定めます。経営者の復帰と商用人格対話は、別々の用途であり続けます。その違いが、公的な約束と背後の私的な判断の双方を形づくります。"), dossier: "succession-directive" },
  contact: { image: "night-city", title: pair("Tokyo sets direction. Night City brings it to the street.", "東京が方針を定め、ナイトシティが現場につなぐ。"), copy: pair("Tokyo anchors corporate direction and the group's industrial identity. Night City connects protective services and Japanese-made products to North American operations. Regional presence is visible in facilities, distribution, and the people who manage access. Headquarters and regional teams connect through the same division structure, while retaining distinct responsibilities.", "東京は企業方針と産業としての基盤を担います。ナイトシティは、警護サービスと日本製品を北米での事業に結びます。地域展開は施設、流通、アクセスを管理する人々の姿として現れます。本社と地域チームは、異なる責任を担いながら、共通の事業構造を通じて連携します。"), target: "security" },
};
